#!/bin/bash
#PBS -N fix_1995_par
#PBS -P gv90
#PBS -q normal
#PBS -l walltime=06:00:00
#PBS -l mem=32GB
#PBS -l ncpus=1
#PBS -l storage=gdata/gv90
#PBS -o /g/data/gv90/xl1657/cmems_adt/notebooks/fix_1995_par.out
#PBS -e /g/data/gv90/xl1657/cmems_adt/notebooks/fix_1995_par.err

module purge
unset PYTHONPATH
source /g/data/gv90/xl1657/venvs/cmems_py311/bin/activate
cd /g/data/gv90/xl1657/cmems_adt/notebooks/
python NB14_fix_1995_and_par_transect.py
